### ISSUE TITLE
Input types with custom scalars in method field resolver

### ISSUE THREAD

**Issue by henrist** [graphql-java-kickstart/graphql-java-tools#198]
I'm trying to use Input types to a mutation with custom scalars (the `ExtendedScalars.Date` from graphql-java-extended-scalars). It fails with an error from Jackson (`Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of java.time.LocalDate (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`). From what I see this is not currently supported, and probably a bug?

When resolving fields for this method, it calls the Jackson object mapper at https://github.com/graphql-java-kickstart/graphql-java-tools/blob/aba01d7157835cd6ab96f76e8ebf394bf8fbe625/src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt#L79

The issue, if I understand correctly, is that the `value` object that is sent to Jackson already contains a proper LocalDate object (the scalar coercing from JSON is already done), and is not a JSON-representation of the input value. The ObjectMapper fails because it builds a TokenBuffer from the `value` (as it expects it to be holding JSON). Then it fails as it tries to deserialize back into a new LocalDate...

Simple schema and mutation class:

```graphql
type Mutation {
  test(input: TestInput!): Boolean!
}
input TestInput {
  value: Date!
}
scalar Date
```

```kotlin
class MutationResolver : GraphQLMutationResolver {
  fun test(input: TestInput): Boolean {
    println(input)
    return true
  }
}
data class TestInput(val value: LocalDate)
```

A bug? Missing feature?

**Comment by oliemansm** [comment]
@henrist Since we're talking about a custom scalar I wouldn't say it's a bug. Although a lot of people probably have this use case, so we might think about making it a bit easier to work with.

You'll have to configure the `ObjectMapper` that's used for supporting dates. This does the trick for me:
```java
objectMapper
    .registerModule(new JavaTimeModule())
    .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
```

You pass in this `ObjectMapper` through the `SchemaParserOptions`:
```java
SchemaParserBuilder parserBuilder;
// ...
SchemaParserOptions parserOptions = SchemaParserOptions.newOptions()
    .objectMapperProvider(fieldDefinition -> objectMapper)
    .build();
parserBuilder.options(parserOptions)
    .build();
```

**Comment by oliemansm** [comment]
@henrist I get your point. Will try to debug a bit to see what's going on. 

Is your concern in the first paragraph only about date time icw Jackson or is it broader related to `graphql-java-tools`?

**Comment by oliemansm** [comment]
@henrist Just did a test without that additional configuration, just as is. Using the scalars from [donbeave/graphql-java-datetime](https://github.com/donbeave/graphql-java-datetime). And using the same test schema from your original description. When I add a breakpoint in the relevant `Coercing` I see that it is in fact using that to parse the date from the input object. So not Jackson.

**Comment by henrist** [comment]
@oliemansm The `Coercing` is working properly. The issue is when this object is then mapped to the argument of the resolver (the code I linked to). When the object is the proper one (e.g. both the coercing gives a LocalDate, and the argument takes an LocalDate), the object is passed through. This happens in the `mapper.convertValue` call. When there is a mismatch the object will be serialized to a json tokenizer and mapped onto the target type.

I'll try to set up a small example repo in one of next days to show what I mean.

**Comment by oliemansm** [comment]
@henrist An example would be very useful, thanks.

**Comment by b4eEX** [comment]
@oliemansm I have an input type that looks like

```graphql

scalar A
scalar B

input MyInput {
    a: A!
    b: B!
}
```
, that fails on the same issue with Jackson. The offending method is `com.coxautodev.graphql.tools.MethodFieldResolver.kt:40`:

```kotlin
return@add mapper.convertValue(value, typeReference)
```

The `value` list actually contains properly handled and converted scalars, but trying to map them to `MyInput` via Jackson fails. I can't use any date parser hacks, since my scalars are not dates.

**Comment by Herlevsen** [comment]
@henrist Did you figure out anything? I am having the same problem

**Comment by brutall** [comment]
So I'm pretty confused with this issue.

I use custom scalar in my input type - scalar serializes to a string. I expected that I need to register my custom serializer/deserializer and this is it. It turned out that I need to register them at both GraphQL and Jackson which surprised me, because they can't both serialize/deserialize the same thing.

I analyzed what is happening internally and it seems the flow is as follows:

1. Coercing.parseValue(String) -> MyCustomScalar
2. JsonSerializer.serialize(MyCustomScalar)
3. JsonDeserializer.deserialize() -> MyCustomScalar

So my scalar is first deserialized (GraphQL), then serialized (Jackson) and deserialized again (Jackson). It does not seem to be right :-)

**Comment by arian** [comment]
We ran into something similar where we have a list of scalars as input argument.

Basically what @brutall said, the GraphQL library already parsed the scalar type into an object.

Then the methodFieldResolver uses the objectMapper to convert that object into an object of that same type... But it could just return the value without converting!

Maybe it's possible to add a check for scalar input types or optionals/lists of scalar types and skip the `mapper.convertValue` call?

**Comment by pramodshri-tgsys** [comment]
I can confirm that this issue is still there in the latest version of `graphql-java-tools`. 

The comments here and in #424 and #436 describes the issue really well so i couldn't add anything more. If anyone knows any work arounds to deal with this when using a third party library class, please let us know.

**Comment by vojtapol** [comment]
@pramodshri-tgsys We would also welcome if you could propose a solution to this.

**Comment by pramodshri-tgsys** [comment]
As noted by brutall [here](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/198#issuecomment-497238174), not going through the process of serializing and deserializing process seems to be the right solution to me.
