### ISSUE TITLE
How to create directive @rest

### ISSUE THREAD

**Issue by khayredinov** [graphql-java-kickstart/graphql-java-tools#263]
When I thy to supply `dataFetcher` through `SchemaDirectiveWiring` without resolver I get `FieldResolverError`.
I want make something like this https://github.com/graphql-community/graphql-directive-rest

**Comment by oliemansm** [comment]
I've updated the sample showing how to use directives, see https://github.com/graphql-java-kickstart/samples/tree/master/directives. Does this help?

**Comment by ringoyip0901** [comment]
Hi @oliemansm  - thank you so much for the example. I'd like to revisit this discussion again. Is the example currently in sync with the latest release? I tried to use the implementation but it wouldn't compile since it was missing "getFieldsContainer(), getDataFetcher(), and getCodeRegistry". 

I have the same implementation in Kotlin: 

`class UppercaseDirective : SchemaDirectiveWiring {
  override fun onField(env: SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition>): GraphQLFieldDefinition {
    val field = env.element;
    val parentType: GraphQLFieldsContainer = env.**getFieldsContainer**();
    // build a data fetcher that transforms the given value to uppercase
    val originalFetcher: DataFetcher<*> = env.registry.**getDataFetcher**(parentType, field)
    val dataFetcher = DataFetcherFactories
        .wrapDataFetcher(originalFetcher, label@ BiFunction { dataFetchingEnvironment: DataFetchingEnvironment?, value: Any? ->
          if (value is String) {
            return@label value.toUpperCase()
          }
          value
        })
    // now change the field definition to use the new uppercase data fetcher
    env.**getCodeRegistry**().dataFetcher(parentType, field, dataFetcher)
    return field
  }
}`

**Comment by oliemansm** [comment]
I updated the example today, so they are definitely in sync now.
