### ISSUE TITLE
SchemaParser#createInputObject issue creating directives

### ISSUE THREAD

**Issue by eferreyramontes** [graphql-java-kickstart/graphql-java-tools#280]
There's a small bug regarding inputObject directives in this line guys:

https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L208

Instead of:

```kotlin
.withDirectives(*buildDirectives(definition.directives, setOf(), Introspection.DirectiveLocation.INPUT_FIELD_DEFINITION))

```

you should have:

```kotlin
.withDirectives(*buildDirectives(inputDefinition.directives, setOf(), Introspection.DirectiveLocation.INPUT_FIELD_DEFINITION))
```

**Comment by elielsonms** [comment]
So, I'm using the 5.5.2 version on my project and I really need this tiny bug resolution on our project. We are avoiding to move to a newer version because that has a graphl-java update and will cause a lot of modifications on our project. Is It possible to generate a 5.5.3 version just including this bug resolution?
