### ISSUE TITLE
How to map a field from a Java class to a type property with a different name?

### ISSUE THREAD

**Issue by Shpota** [graphql-java-kickstart/graphql-java-tools#383]
I have a type definition with a filed that has underscores in its name:
```
type Book {
    reviews_count: Int
}
```
**Q:** Is there a possibility to use `reviewsCount` instead of `reviews_count` in Java code? (an analog of `@JsonProperty` from Jackson)

Note: I do not want to remap all camel case notations to type properties with underscores. It is only needed for this particular field.

**Comment by plaurina** [comment]
Ran into the same issue due to CamelCase being more conventional in Java.  My main issue revolved around JWKs (Json Web Key) where the [spec](https://tools.ietf.org/html/rfc7517#:~:text=Introduction-,A%20JSON%20Web%20Key%20(JWK)%20is%20a%20JavaScript%20Object%20Notation,represents%20a%20set%20of%20JWKs.&text=JWKs%20and%20JWK%20Sets%20are,Web%20Encryption%20%5BJWE%5D%20specifications.) for it has the field "key_ops". 

My POJOS are generated from a json-schema that is shared between our front and backend code bases as our contract between each layer. Otherwise I'd have put a helper method in the POJO, or an annotation, or some other method.  Editing generated classes manually is of course a maintenance nightmare waiting to happen.

I have created a PR that I hope will get accepted - the `FieldResolverScanner.findResolverMethod()` had a 4 checks for a variety of ways to find the method give a field name.  I added a 5th way, where if none of the other 4 are found, then it will convert a snake_case field name to camel case and check for a getter.  ie.    `"key_ops"` -> `getKeyOps()`
